build_from:
  amd64: ghcr.io/home-assistant/amd64-base:latest
  aarch64: ghcr.io/home-assistant/aarch64-base:latest
labels:
  org.opencontainers.image.title: Wizard
  org.opencontainers.image.description: Wizard Kartenspiel – Online Multiplayer
  org.opencontainers.image.source: https://github.com/GianlucaKo95/wizard
  org.opencontainers.image.licenses: MIT
